### ISSUE TITLE
Add support for "renderaction" in buttons

### ISSUE THREAD

**Issue by agarciadom** [mdenet/educationplatform#101]
The `epsilon_tool.json` file in the example `static.epsilon` project includes a button for rendering the model/metamodel as a diagram, which uses a `renderaction`:

https://github.com/mdenet/platformtools/blob/main/static.epsilon/public/epsilon_tool.json#L286

I understand that the purpose of this button is to reproduce the behaviour in the Epsilon Playground, which has a similar button:

![image](https://github.com/mdenet/educationplatform/assets/46504/eaf84d33-ff77-46f4-b921-abb34a6cea99)

I cannot find any reference to `renderaction` in the platform's source code, however. The equivalent buttons show up in the UI, but they do not do anything when clicked.

Are there any plans to add this? I'll have to remove this button for the time being from my tutorial.

**Comment by agarciadom** [comment]
I have worked around this by using an actionfunction instead, and having a button action that sends the diagram to a different panel. See here for this example:

https://github.com/agarciadom/mdenet-mde-ci-tutorial/blob/main/state-machines.yml

I still think that supporting `renderfunction` would produce something more elegant.

**Comment by yamtl** [comment]
+1 for this feature request

At the moment I'm also using the workaround that Antonio is using for the [YAMTL playground](https://yamtl.github.io/playground/?activities=https://yamtl.github.io/playground-activities/yamtl-cd2db-activity.json).

**Comment by arturboronat** [comment]
The pull request #134 provides a generalization of Model/Metamodel panels.

**Comment by barnettwilliam** [comment]
This is now achieved through the use of composite panels introduced in c8592781101c8afeb2e79b8cd3bf46477dcf00f1.
