### ISSUE TITLE
Support for using language workbench outputs in activities

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#173]
The platform should support activities where the output of language workbenches can be used, for example, model-to-model transformations using ETL of the created language. 

- [x] Create an example activity

#### Input conversion
Modify the Epsilon ETL tool service to accept XMI inputs.
- [x] #177

#### Output conversion
Add support for automatic conversion of platform tool function outputs.
- [ ] tool function output type conversion

**Comment by barnettwilliam** [comment]
Activity created and available on branch [mdenet/platform-examples-private/activity-using-xtext-output](https://github.com/mdenet/platform-examples-private/tree/activity-using-xtext-output)

**Comment by szschaler** [comment]
The activity currently doesn't have an action for running the ETL. I assume this is to be defined?

**Comment by barnettwilliam** [comment]
Yes, I'm currently modifying the Epsilon micronaut function to accept Xmi and will add it when testing

**Comment by barnettwilliam** [comment]
@szschaler while trying to test the modified micronaut service, there is a difference between what platform type conversion expects when the type is a model. 

The **to-xmi** function that's generated by the Xtext build doesn't take a metamodel as an input, presumably it already has this, but because the target type is model the platform expects the conversion function to have a corresponding metamodel. The platform fails to find a matching conversion function as the required metamodel is missing.

We could either: 
1. Create an exception in the type conversion for all `*-generated` types so that a metamodel is not required for the model conversion.
2. Add a metamodel as an input parameter of to the xtext **to-xmi** function, the tool function doesn't necessarily need to use it

**Comment by barnettwilliam** [comment]
> Activity created and available on branch [mdenet/platform-examples-private/activity-using-xtext-output](https://github.com/mdenet/platform-examples-private/tree/activity-using-xtext-output)

The example activity is working as of [commit](https://github.com/mdenet/platform-examples-private/commit/47414aa12ba0c345f9030dc08f3dca78006242e6) when used in conjunction with the modified Epsilon tool service pending PR https://github.com/epsilonlabs/playground-micronaut/pull/1 and PR https://github.com/mdenet/platformtools/pull/56 fixed Xtext project file structure.

The error in the original turtles-copy example that has identical metamodels should be fixed separately as suggested https://github.com/epsilonlabs/playground-micronaut/issues/2#issuecomment-1941443293.

#### Deferred https://github.com/mdenet/platformtools/pull/56 support
So that https://github.com/mdenet/platformtools/pull/56 can be deferred to support the ongoing module teaching, the following branch provides a version of the example activity in the original Xtext project structure.
https://github.com/mdenet/platform-examples-private/tree/activity-using-xtext-output-old-project

**Comment by szschaler** [comment]
For the current use case, we don't need function output conversion, so this is complete.
