### ISSUE TITLE
Epsilon tool service XMI support 

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#177]
The Epsilon micronaut tool services should support XMI model as inputs so language workbench outputs can be used in activities.

**Comment by szschaler** [comment]
I would go with the second option.

**Comment by barnettwilliam** [comment]
XMI Epsilon support in PR https://github.com/epsilonlabs/playground-micronaut/pull/1
 
Suggested change in https://github.com/mdenet/platformtools/pull/57, only required configuration file update.
