### ISSUE TITLE
Clean up Epsilon Wrapper so that functions only expect the parameters they are actually using

### ISSUE THREAD

**Issue by szschaler** [mdenet/educationplatform#41]

**Comment by barnettwilliam** [comment]
The new epsilon micronaught services https://github.com/epsilonlabs/playground-micronaut support this and provide education platform support. We should transition to using these and remove epsilon from our mdenet/platformtools.

**Comment by barnettwilliam** [comment]
Linked branch with fix for this issue and submitted PR https://github.com/mdenet/educationplatform/pull/198#discussion_r1531961177 to the Epsilon micronaut to update the tool configuration file to include only required parameters.
