### ISSUE TITLE
tool highlighting rules not version controlled

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#54]
The tool highlighting js rules that are bundled for testing in mdenet/educationplatform/test/toolconfig[tool name] are not currently version controlled.

I suggest that the js highlighting rules for each tool are added to the mdenet/platformtools/static.[tool name] and the correspondiong icons, icons.css, and tool config file are relocated from mdenet/educationplatform/test/toolconfig[tool name]  to  same place.  The this is because the static highlighting/icons/toolconfig  need to be made available along with the tool services. 

This would affect the current education platform demo launch used for initial testing but we plan to add a separate repository https://github.com/mdenet/educationplatform/issues/26#issuecomment-1521641615

**Comment by szschaler** [comment]
Fixed by https://github.com/mdenet/platformtools/pull/4
