### ISSUE TITLE
OCL tool error on repeated clicks

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#60]
While using the OCL example if the run button is pressed quickly and repeatedly,  an error message is shown in the output console which then doesn’t seem to recover. 

Thee could be some some overload on the backend that’s not managed correctly…

**Comment by barnettwilliam** [comment]
Check dispose is called properly from the OCL java API

**Comment by szschaler** [comment]
Closed: the problem appears to have gone away and is no longer reproducible.
