### ISSUE TITLE
Tokenserver documentation

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#69]
Create documentation on how to setup and use the toolserver for private git repositories.

**Comment by barnettwilliam** [comment]
Added to wiki in commit https://github.com/mdenet/educationplatform/wiki/Setting-up-the-Platform/42aedb7f0aad17f42e2fa17c636e5ced4291aa53

**Comment by barnettwilliam** [comment]
@szschaler ready to review: https://github.com/mdenet/educationplatform/wiki/Setting-up-the-Platform

**Comment by szschaler** [comment]
Looks good to me, though it may be useful to also say what the `TOKEN_HANDLER_URL` would have to be set to :-)

**Comment by barnettwilliam** [comment]
Added format and example for the `TOKEN_HANDLER_URL`
