### ISSUE TITLE
Perform validation of activity YAML before start

### ISSUE THREAD

**Issue by agarciadom** [mdenet/educationplatform#97]
It would be good to do a thorough validation of the activity YAML before you run it. For instance, just checking the basic referential integrity of the YAML, e.g. that you don't have an action refer to a panel that does not exist. At the moment, doing this just results in an odd error message in the JavaScript console that a user has to debug manually.

This may be solved by defining a schema for activities, but you could also just write a validation routine that traverses the YAML and performs those basic checks, based on the specification in the wiki.

**Comment by barnettwilliam** [comment]
Schema-based validation of the config files has been added in #104. Further validation will be added as part of #37.
